openai:
  api_key: $OPENAI_API_KEY
  chat_model: "gpt-4-32k"
  temperature: 0.0
  max_tokens: 256
  model_transcript: "whisper-1"
  model_transcript_language: "en"
  embedding_model: "text-embedding-ada-002"
  model_tts: "tts-1"
  voice_tts: "shimmer"

pinecone:
  api_key: $PINECONE_API_KEY
  environment: $PINECONE_ENVIRONMENT

prompts:
  chat:
    filepath: "./src/prompts/chat/system.txt"

  functions:
    filepath: "./src/prompts/functions/signatures.json"

